### ISSUE TITLE
Bundle size

### ISSUE THREAD

**Issue by atinux** [thetutlage/vue-clip#1]
I think there is a bug in the bundling process:

I use [package-size](https://github.com/egoist/package-size) to check the sizes of vue and vue-clip:
```
package   size    minified  minified + gzipped
vue       162 kB  51.4 kB   18.4 kB
vue-clip  164 kB  59.1 kB   17.8 kB
```

When I checked the source code of your project (`src` folder), it can't be possible that it's as big a Vue.js, maybe Webpack is putting vue inside the bundle?

**Comment by thetutlage** [comment]
Nope http://www.dropzonejs.com is 40KB alone, so that increases the size.

I have plans to implement the core file upload library by hand, which will be transparent change for the API consumers.

**Comment by atinux** [comment]
I was checking the dependencies and saw dropzonejs :)

Anyway, great component, keep up the good work 👏
