### ISSUE TITLE
Flush Items after Upload

### ISSUE THREAD

**Issue by mstaack** [thetutlage/vue-clip#11]
Given i am using this in a bootstrap modal.

How can i flush the items in the file.props array?  so after opening the modal again the items are not present anymore..

far the best upload plugin for vuejs! really awesome
thanks max

**Comment by thetutlage** [comment]
You can access the uploader instance by using `onInit` event http://vueclip.adonisjs.com/#-events and then reset the array anytime you want by using the uploader instance. The following should work

```html
<template>
  <vue-clip :on-init="init">
  </vue-clip>
</template>

<script>
  export default {

    data: {
       uploader: null
    },

    methods: {
      init (uploader) {
         this.uploader = uploader
      },

      showDialog () {
           this.uploader.files = []
       }
    }

  }
</script>
```

**Comment by mstaack** [comment]
Awesome! Will give it a try!

**Comment by mstaack** [comment]
@thetutlage one more question:

after complete fileupload i am adding the response back into my data array like this:

```
            complete: function (file, status, xhr) {
                if (status === 'success') {
                    this.items.push(JSON.parse(xhr.response))
                }

```

is there a better way to add as json then using `JSON.parse`?  like telling xhr its json or something?

**Comment by oanstein** [comment]
With "this.uploader" set you can use all the [dropzone.js methods](http://www.dropzonejs.com/#dropzone-methods). 

If you want to remove all files, simply use **this.uploader.removeAllFiles()**. Files that are in the process of being uploaded won’t be removed. If you want files that are currently uploading to be canceled, call .removeAllFiles(true) which will cancel the uploads.
