### ISSUE TITLE
acceptedFiles.split is not a function

### ISSUE THREAD

**Issue by vkruoso** [thetutlage/vue-clip#17]
When using the syntax below I'm getting an error in the console saying that ``acceptedFiles.split is not a function``. Switching to the object syntax, there is no error. 

```
{
  acceptedFiles: ['image/*', 'application/pdf']
}
```

**Comment by thetutlage** [comment]
yup will fix it, for now a comma separated string will work too `image/*,application/pdf,.psd`

**Comment by vkruoso** [comment]
Great! Thanks for such great component.

**Comment by abishekrsrikaanth** [comment]
@thetutlage,  I tried both the suggestions
```
acceptedFiles: ['image/png, image/jpg, application/eps']
```
and
```
acceptedFiles: ['image/png', 'image/jpg', 'application/eps']
```
both seems to throw the same error.

**Comment by alexsasharegan** [comment]
@thetutlage I believe my [PR 21](https://github.com/thetutlage/vue-clip/pull/21) should clear this up and conform to your prop options as declared in the readme.

**Comment by alexsasharegan** [comment]
@abishekrsrikaanth ,

The current release will only handle a string or object. Here are your options:
- raw string
```js
acceptedFiles: 'image/png, image/jpg, application/eps'
```
- object
```js
acceptedFiles: {
  extensions: ['image/png', 'image/jpg', 'application/eps']
}
```
- quick fix to your existing array setup
```js
acceptedFiles: ['image/png', 'image/jpg', 'application/eps'].join(',')
```

**Comment by abishekrsrikaanth** [comment]
@alexsasharegan  👍 thank you

**Comment by ghost** [comment]
how to accept all kind of types?

**Comment by alexsasharegan** [comment]
I believe you can just omit passing the `acceptedFiles` prop to get all files, @huaoxiang .

**Comment by Riturajvaishnav2** [comment]
accept: ['.jpg', '.png'],

**Comment by Riturajvaishnav2** [comment]
accept: ['image/*']
or
accept: ['.jpg', '.png'],=
or
accept: ['application/vnd.ms-excel', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'],
