### ISSUE TITLE
[Bug] Component is missing destroy logic

### ISSUE THREAD

**Issue by alexsasharegan** [thetutlage/vue-clip#26]
This component initializes the Dropzone element under the hood, but it does not implement clean up logic.

**Comment by alexsasharegan** [comment]
Looks like an easy fix.

In the clip component:
```js
{
    destroyed() {
        this.uploader.destroy()
    },
}
```

And a tweak to the Uploader class:
```js
class Uploader {
    destroy() {
        // this._uploader.disable()
        this._uploader.destroy()
    }
}
```

**Comment by alexsasharegan** [comment]
Found that Dropzone has an option called `hiddenInputContainer`. An element in the vue-clip component should be created with a uniquely generated id to facilitate this. This will allow vuejs to handle cleanup and avoid leaking nodes in a dynamically created vue-clip instance.

**Comment by thetutlage** [comment]
👍  Will work on it

**Comment by alexsasharegan** [comment]
Here's some ammo for the changes:

```vue
<template>
    <div :class="uploaderClass">
        <slot name="clip-uploader-action"
              :is-dragging="isDragging"></slot>
        <slot name="clip-uploader-body"
              :files="files"></slot>
        <div ref="clip-preview-template"
             class="clip-preview-template"
             style="display: none;">
            <div></div>
        </div>
        <div :id="hiddenInputId"></div>
    </div>
</template>

<script>
{
    data() {
        const hiddenInputId = `dz-hidden-input-container-${uniqueId()}`

        return {
            files: [],
            dragCounter: 0,
            uploader: null,
            hiddenInputId,
        }
    },

    mounted() {
        const options = Object.assign(clone(this.options), { hiddenInputContainer: `#${this.hiddenInputId}` })
    }
}
<script/>
```

**Comment by DwayneHawkins** [comment]
Easy but still not fixed :(

**Comment by alexsasharegan** [comment]
@UsernamesAreOutdated, I've taken to creating my own Dropzone vue implementation since this project has grown stale. Have a look to see if it may suit your needs better: https://github.com/alexsasharegan/vue-transmit

**Comment by alexsasharegan** [comment]
I'm closing this to clean up my personal outstanding issues.
