### ISSUE TITLE
How to delete uploaded file? 

### ISSUE THREAD

**Issue by yfxie** [thetutlage/vue-clip#28]
I saw the method `onRemovedFile(file)` on README. the method will be invoked when the file was deleted. 
but it seems there is no way to delete uploaded file. I have read source code.

what I need is the method `DELETE(file)` as following:

```
<template slot="clip-uploader-body" scope="props">
  <div v-for="(file, index) in props.files">
    <img v-bind:src="file.customAttributes.thumb_url" v-on:click="DELETE(file)"/>
    {{ file.name }} {{ file.status }}
  </div>
</template>
```

Clip#removeFile is the method I want. but I can't call the method inside `clip-uploader-body` slot, it's different scope.

refer this: https://vuejs.org/v2/guide/components.html#Compilation-Scope

**Comment by alexsasharegan** [comment]
Couldn't you proxy the method call by adding a method on your component using vue-clip?

```vue
<template slot="clip-uploader-body" scope="props">
  <div v-for="(file, index) in props.files">
    <img v-bind:src="file.customAttributes.thumb_url" v-on:click="removeFile(file)"/>
    {{ file.name }} {{ file.status }}
  </div>
</template>

<script>
{
  components: {VueClip},
  methods: {
    removeFile(file) {
      this.$refs.vue_clip.removeFile(file)
    }
  }
}
</script>
```
You'll just need to add a ref to the vue-clip instance so you can call its methods.

**Comment by cristian-gherghel** [comment]
i will try tomorrow and let you know if it works :) 
thank you!

**Comment by yfxie** [comment]
Yes, your code is actually the way I am using. by using $refs to ref VueClip instance and call removeFile. it works.

**Comment by yfxie** [comment]
I suggest we should put the way to README. it's common requirement but I found the way by digging source code. on README there is only description about event hook.

Thanks for your reply

**Comment by alexsasharegan** [comment]
@yfxie, that's a good idea. I don't have any commit permissions, but anyone can PR that. Any other key _gotchas_ like this?

**Comment by cristian-gherghel** [comment]
sorry, not working for me. I made the ref="vc" on vue-clip tag,
then created the methods: { removeFile(file) { this.$refs.vs.removeFile(file) } },
then @click="removeFile(file)" on img tag, and result: this.$refs.vc.removeFile is not a function.

I guess i miss something here, but i don't realize it yet :)

PS: i have uninstalled npm unistall vue-clip, and reinstalled it.

**Comment by yfxie** [comment]
@electronrecord can you provide snippet code?

**Comment by electronrecord** [comment]
`<vue-clip ref="vc" :options="options"
                  :on-complete="Complete"
                  :on-sending="Sending"
                  :on-added-file="Uploading">
          <template slot="clip-uploader-action">
            <div>
              <div class="dz-message"><h2 @click="Set_Index(index)"> + </h2></div>
            </div>
          </template>

          <template slot="clip-uploader-body" scope="props">
            <div v-for="file in props.files">
              <img v-bind:src="file.dataUrl" @click="removeFile(file)" />
              <h2 class="progress-bar">
                loading: {{ Math.floor(file.progress) + "%" }}
              </h2>
            </div>
          </template>

        </vue-clip>`
`methods: {
      removeFile (file) {
        this.$refs.vc.removeFile(file)
      }
    },`

**Comment by yfxie** [comment]
@electronrecord sorry, information is not enough for me.

**Comment by cristian-gherghel** [comment]
<vue-clip ref="vc" :options="options">

          <template slot="clip-uploader-action">
            <div>
              <div class="dz-message"><h2 @click="Set_Index(index)"> + </h2></div>
            </div>
          </template>

          <template slot="clip-uploader-body" scope="props">
            <div v-for="file in props.files">
              <img v-bind:src="file.dataUrl" @click="removeFile(file)" />
              <h2 class="progress-bar">
                loading: {{ Math.floor(file.progress) + "%" }}
              </h2>
            </div>
          </template>

        </vue-clip>

 ```
<script>
  export default {
    name: 'gallery',
    data () {
      return {
        options: {
          url: '/upload_gallery',
          paramName: 'file',
          maxFiles: 1
        }
      }
    },
    computed: {
      templates () {
        return this.$store.state.templates
      },
      profile () {
        return this.$store.state.profile
      }
    },
    methods: {
      Set_Index (index) {
        this.picIndex = index
      }
      removeFile (file) {
        this.$refs.vc.removeFile(file)
      }
    },
    mounted () {
      this.$store.commit('Set_Pet_Pics')
    }
  }
</script>
```

Vue-clip version:

 "name": "vue-clip",
  "version": "1.0.0",

**Comment by yfxie** [comment]
@electronrecord  what's version of your vue ?
does your options work? and is options above methods?
can you provide entire code of the component

**Comment by electronrecord** [comment]
oops, my mistake, i have uploaded the code above (with options). Still, where should the removeFile function came from? from vue-clip package?
 "name": "vue-clip",
  "version": "1.0.0",

**Comment by yfxie** [comment]
I mean `<script>export default { ... }</script>`

and you put methods on wrong place

```
options: {
         url: '/upload_gallery',
         paramName: 'file',
         maxFiles: 1
       },
 methods: {
     removeFile (file) {
       this.$refs.vc.removeFile(file)
     }
   },
```

should be

```
data() {
  return { options: { ... } }
},
methods: {
  removeFile(file) { ... }
}
```

**Comment by cristian-gherghel** [comment]
(i'm a bit of an "idiot" :) ) sorry again for not writting the full code, i have updated the above, in order to not make a mess on here.

**Comment by alexsasharegan** [comment]
P.S. I forked this repo in favor of a more event-driven style. Basically removed all the callback hooks and went straight to the dropzone.js source to proxy all their events using Vue's excellent event interface. This lets me just use the vue event binding syntax in the template (more idiomatic vue). Like so:

```vue
<vue-dropzone class="vue-dz"
                      ref="dz"
                      :options="uploaderConfig"
                      @upload-start="onUploadStart"
                      @upload-complete="onUploadEnd"
                      @success="onSuccess"
                      @error="onError"></vue-dropzone>
```

Not sure if you have more time to source dive, @yfxie, but I'm curious what people think. You can find it here: https://github.com/alexsasharegan/vue-clip

My thoughts are moving towards porting dropzone.js from coffeescript source to es2015 modules and maybe make it a native Vue lib so I won't have to reinvent the emitter class (lighten up the source code).

**Comment by alexsasharegan** [comment]
P.S. @yfxie I started the work of porting Dropzone over at this repo: https://github.com/alexsasharegan/vue-transmit. Feel free to contribute!
