### ISSUE TITLE
method always is OPTIONS

### ISSUE THREAD

**Issue by toby3d** [thetutlage/vue-clip#39]
I run small local router with POST trigger, but after select any file I get arror:
![image](https://user-images.githubusercontent.com/5412322/28958877-8d690914-7911-11e7-8a61-dcc0e02d2fe5.png)
logs
```go
{"time":"2017-08-04T12:31:44.60323609+05:00","id":"","remote_ip":"127.0.0.1","host":"127.0.0.1:1323","method":"OPTIONS","uri":"/","status":405, "latency":43517,"latency_human":"43.517µs","bytes_in":0,"bytes_out":37}
```

My code in `.vue` file (after import and use module in `main.js`):
```javascript
export default {
  name: 'app',
  data() {
    return {
      tips: true,
      locale: 'en',
      options: {
        url: apiUrl,
        method: 'post',
        paramName: 'file',
        maxFileSize: {
          limit: 99,
          message: '{{ filesize }} is greater than the {{ maxFilesize }}'
        }
      }
    }
  }
}
```

**Comment by toby3d** [comment]
- Remove method -> OPTIONS method
- 'post' method -> OPTIONS method
- 'POST' method -> OPTIONS method
- 'GET' method -> OPTIONS method

**Comment by thetutlage** [comment]
The OPTIONS request is made by browser when its a cross domain request, just read more about CORS

**Comment by toby3d** [comment]
@thetutlage Oh, shit, I'm sorry. :no_mouth:
