### ISSUE TITLE
Progress for each file

### ISSUE THREAD

**Issue by aleksandrmelnyk** [thetutlage/vue-clip#42]
Hi,

is there a way to get progress for each file separately, for example to show progress against each file?

thanks.

**Comment by alexsasharegan** [comment]
You can use a scoped slot to obtain a reference to the files on the uploader component. Then you can access `file.upload.progress`.

```vue
<template>
  <clip>
    <template slot="clip-uploader-body"
              scope="props">
      <span v-for="file in props.files">{{ file.upload.progress }}</span>
    </template>
  </clip>
</template>
```

**Comment by aleksandrmelnyk** [comment]
nice one, thanks
