### ISSUE TITLE
How to configure global options?

### ISSUE THREAD

**Issue by kcifuentes** [thetutlage/vue-clip#43]
Hello, I have a doubt, in my project it is necessary to configure the option headers in a global way in order not to have to instantiate it every time I use the vue-clip component.

I Would like to know if there is any way to do this?

Thank you and forgive my bad English, I'm Spanish speaking...

**Comment by alexsasharegan** [comment]
You could always define your headers in a separate file and import them each time you use an uploader.

**Comment by kcifuentes** [comment]
Thanks, @alexsasharegan.
