### ISSUE TITLE
How can i remove the file from the uploaded list

### ISSUE THREAD

**Issue by medspec** [thetutlage/vue-clip#46]
without a refresh it current holds all the upload in internal data, so not accessabel.
When an upload is successfull i want te remove it from the list, how can i access that file list?

**Comment by medspec** [comment]
sorry, i see now there is a pull request for it #28

**Comment by alexsasharegan** [comment]
For reference, I think you mean the PR at #29

**Comment by medspec** [comment]
Yeah the pull is #29  the underlying issue #28 
thanks!
