### ISSUE TITLE
Method to reset inner reference of files

### ISSUE THREAD

**Issue by hpaul** [thetutlage/vue-clip#47]
Hello,

I suggest a new method which could be called to reset the array of fields from `vue-clip` data.
But this should not trigger `onRemovedFile` event, because you just want to remove files which template render.

Something like:
```js
resetFiles() {
    this.files = [];
}
```

So you can call
```js
this.$refs.uploader.resetFiles()
```

It's small, but very useful sometimes.

**Comment by prakashpie** [comment]
yes, very required functionality...
