### ISSUE TITLE
[Question] How to use withCredentials in vue-clip?

### ISSUE THREAD

**Issue by alwayszb** [thetutlage/vue-clip#48]
How to send files with cookie credentials in vue-clip?

**Comment by alexsasharegan** [comment]
You should be able to use the `headers` option to pass your cookie credentials.

**Comment by alwayszb** [comment]
@alexsasharegan Could you give an example for better understanding? Thanks!

**Comment by alexsasharegan** [comment]
I think I would need to understand your use case better first. Roughly what are trying to send? What are you expecting the XHR to look like?

**Comment by alwayszb** [comment]
I just want `xhr.withCredentials = true`, so the upload request could carry the cookie credentials, because the upload operation needs login authority.

**Comment by alwayszb** [comment]
@alexsasharegan I found out a solution: set `xhr.withCredentials = true` in `onSending` event, it solved my problem. Thanks for your help!

**Comment by alexsasharegan** [comment]
You should also be able to include in your options props passed to vue-clip:
```js
const options = {
  // ...
  withCredentials: true
  // ...
}
```

http://www.dropzonejs.com/#config-withCredentials

**Comment by alwayszb** [comment]
Awesome! Using `withCredentials: true` in options is a more reasonable and efficient way.
