### ISSUE TITLE
Upload files with Laravel

### ISSUE THREAD

**Issue by bee-interactive** [thetutlage/vue-clip#54]
Hi!

I'm trying to make it work with laravel but for now, nothing seems to work. I can't get the file data on the Laravel side. The example shown in the video use another routing system. 

Is this component compatible with Laravel? How can I achieve to pass the datas to my Laravel controller?

Thanks in advance!

**Comment by juhasev** [comment]
I am assuming you are getting 419. If so make sure you tell the vue-clip to pass the XMLHttpRequest and CSRF token headers. If you are using vanilla Laravel these are already attached to Axios by default.

```javascript
window.axios.defaults.headers.common['X-Requested-With'] = 'XMLHttpRequest';
window.axios.defaults.headers.common['X-CSRF-TOKEN'] = token.content;
```
All what you need to do is to pass these in the vue-clip options array:
```javascript
        data() {
            return {
                options: {
                    url: '/upload',
                    headers: window.axios.defaults.headers.common
                }
            }
        }
```
Processing in your controller can be done like this:

```php

namespace App\Http\Controllers\PanelistImporter;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class UploadController extends Controller
{
    public function save(Request $request)
    {
        $file = $request->file('file');

        return response([
            'message' => 'uploaded',
            'filename' => $file->getClientOriginalName(),
            'size' => $file->getClientSize()
        ], 200);
    }
}
```

**Comment by bee-interactive** [comment]
Thanks, worked great for me! Have a good day!
