### ISSUE TITLE
Cloud Storage upload?

### ISSUE THREAD

**Issue by jyoungqu** [thetutlage/vue-clip#61]
Hi guys! Firstly, this is a pretty sweet uploader and well thought out. I've not dug into the depths just yet but wanted to see if there were some pointers on getting this easily integrated into my current needs which uses Firebase Storage which is built on top of Google Cloud Storage (https://firebase.google.com/docs/storage/web/start) I'm in the process if ripping out jQuery based code and replacing with Vue (Vuetify).

Any pointers that can get me off and in the races is greatly appreciated!

**Comment by alexsasharegan** [comment]
@jyoungqu, you should check out https://github.com/alexsasharegan/vue-transmit. I've been hacking on a Firebase driver to make interfacing easy. 

I would try forking/cloning `master` locally and playing with the test app. The test app has a sub-package of sorts (requires a separate npm install). You'll need to drop in a `test/server/.firebase.json` file with your own credentials too to connect to your firebase instance.

```json
{
  "apiKey": "...",
  "authDomain": "<...>.firebaseapp.com",
  "databaseURL": "https://<...>.firebaseio.com",
  "projectId": "...",
  "storageBucket": "<...>.appspot.com",
  "messagingSenderId": "..."
}
```

**Comment by jyoungqu** [comment]
Thanks @alexsasharegan - Taking a look at the vue-transmit setup doesn't fit my needs as is since what I currently do is direct uploads from client to cloud storage with the firebase SDK for storage - so no server side solution.

**Comment by alexsasharegan** [comment]
@jyoungqu , I don't think you understood. The test app uses a server to serve the test app an hide credentials from github. You don't have to use it, but it's exactly what you're looking for.

**Comment by joemanfoo** [comment]
@alexsasharegan - Hmm, I took a look at the client side and didn't see anything jumping out at me as being plugin for the firebase storage sdk. I'll take another look. Thank you.

Yep, totally didn't look close enough - thanks again Alex!

**Comment by alexsasharegan** [comment]
@joemanfoo , it's still in alpha, but I do have a firebase driver you can pop in. Got it working a little while back, but just need to steal some more time to refine it! Feel free to drop in issues over there!
